### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by HJJKnight** [kaina404/DouBanProject#74]
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by HJJKnight** [comment]
修改android/gradle\wrapper/gradle-wrapper.properties，distributionUrl=https\://services.gradle.org/distributions/xxx.zip ，更改为本地有的 gradle 版本

**Comment by Palchetan07** [comment]
Any solution you proposed to deal with this error.

**Comment by huangchengzuo** [comment]
你好！
邮件已收到！谢谢！

**Comment by Palchetan07** [comment]
English
